### ISSUE TITLE
Cannot import Qualtrics from qualtrics-api

### ISSUE THREAD

**Issue by Agugori** [Miramac/node-qualtrics-api#21]
Hello there, im trying to import Qualtrics but i got this error
 `'Qualtrics' can only be imported by using 'import Qualtrics = require("qualtrics-api")' or by turning on the 'esModuleInterop' flag and using a default import.ts(2617)`

this is the way im importing it, im already try to do it without the breakets

![Captura de pantalla 2023-01-29 a la(s) 11 16 40](https://user-images.githubusercontent.com/100368279/215332438-53d5a9a9-3f6d-4ee1-8c3a-37015ad33564.png)

this is my tsconfig.ts

![Captura de pantalla 2023-01-29 a la(s) 11 17 46](https://user-images.githubusercontent.com/100368279/215332484-c03587a2-c1e9-466e-af7c-22d2535438b5.png)

**Comment by Agugori** [comment]
im using it on a nestjs app

**Comment by Miramac** [comment]
sorry for the late response...
For now you have to use this: `import Qualtrics = require('qualtrics-api');`. I will probably change it in the future

This code worked for me without turning on the 'esModuleInterop' flag.
````ts
import { Controller, Get } from '@nestjs/common';
import { AppService } from './app.service';
import Qualtrics = require('qualtrics-api');

const config = {
  apiToken: '<apiToken>',
  baseUrl: 'https://eu.qualtrics.com/API/v3/',
  defaultDirectory: '<defaultDirectory>',
};
const qualtrics = new Qualtrics(config);

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  async getHello(): Promise<string> {
    return qualtrics.whoami();
  }
}

````
